workdir: /home/vagrant
sandbox_owner: vagrant
sandbox_group: vagrant
# The number of threads to use for building Contrail
scons_tasks: 4
contrail_package_repository: http://172.17.0.1:6667/
# static alternative: http://148.251.5.90/38978-1/
kolla_docker_registry: ""
kolla_docker_namespace: jlukcodi
