#- name: Install and run docker on VM
#  yum:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - docker
#  notify:
#    - Restart docker service
#  become: yes
#  become_user: root

#- name: start docker
#  service:
#    name: docker
#    state: started

- meta: flush_handlers

- import_tasks: lighttpd.yaml

- import_tasks: registry.yaml

