- name: Install and run docker on VM
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
  become: yes
  become_user: root

- name: Restart docker service
  service:
    name: docker
    state: started
  become: yes
  become_user: root

- import_tasks: lighttpd.yaml

- import_tasks: registry.yaml

