- name: Start local docker registry
  docker_container:
    name: local_registry
    image: registry
    state: started
    restart_policy: always
    published_ports:
      - 6666:5000
#  register: local_registry_deployed
  become: yes
  become_user: root

#- name: Configure insecure local registry
#  copy:
#    content: |
#      {
#        "insecure-registries": ["{{ docker_container.NetworkSettings.IPAddress }}:5000"]
#      }
#    dest: /etc/docker/daemon.json
#  notify:
#    - Restart docker service
#  when: local_registry_deployed.changed
#  become: yes
#  become_user: root

#- meta: flush_handlers

