- name: Install dependencies needed for Contrail build
  yum:
    name: "{{ item }}"
  with_items:
    - python-lxml
    - autoconf
    - automake
    - libtool
    - patch
    - unzip
    - wget
    - kernel-devel
    - rpm-build
    - scons
    - yum-utils
  become: yes
  become_user: root

