- name: Install kernel dependencies
  yum:
    name: "{{ item }}-{{ kernel_version }}"
  with_items:
   - kernel
   - kernel-devel
   - kernel-tools
   - kernel-tools-libs
  become: yes
  become_user: root

- name: Install dependencies needed for Contrail build
  yum:
    name: "{{ item }}"
  with_items:
    - python-lxml
    - autoconf
    - automake
    - libtool
    - patch
    - unzip
    - wget
    - rpm-build
    - scons
    - yum-utils
  become: yes
  become_user: root

