- name: Prepare inventory hosts.yaml used by CI playbooks
  copy:
    src: "../templates/inventory"
    dest: "/home/vagrant/code"
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Setup config file for Ansible run inside VM
  copy:
    content: |
      [defaults]
      roles_path = /home/vagrant/code/contrail-project-config/roles:/home/vagrant/code/zuul-jobs/roles
    dest: /home/vagrant/.ansible.cfg
    mode: 0644
    owner: vagrant
    group: vagrant


- name: Create sandbox dir
  file:
    path: "/home/vagrant/contrail-5.0"
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Configure git client
  git_config:
    name: "{{ item.option }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { option: user.name, value: 'Your Name' }
    - { option: user.email, value: 'you@example.com' }
    - { option: color.ui, value: 'true' }

- name: Initialize repo dir
  shell: |
    repo init --no-clone-bundle -u https://github.com/Juniper/contrail-vnc -b master
  args:
    chdir: /home/vagrant/contrail-5.0

- name: Sychronize repo dir with upstream
  shell: |
    repo sync --no-clone-bundle -j 4
  args:
    chdir: /home/vagrant/contrail-5.0

